import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className='flex  place-content-around bg-slate-500 p-6'>
        <h1>Pet finder</h1>
        <div className=' space-x-6'>
          <a href="/">Sobre</a>
          <a href="/">Perdi meu cachorro</a>
          <a href="/">Encontrei um cachorro</a>
          <a href="/">Contatos</a>
        </div>
        <Link href='/create_account'>
          Criar uma conta
        </Link>
      </nav>

      <div className='p-16'>
        <div className='flex place-content-between align'>
          <p className='font-bold text'>Cachorros pedidos</p>
          <p>Goiânia - 65km</p>
        </div>
      </div>

    </>
  )
}
